name: "Release Published to Discord"
on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Notify Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "3371747"
          username: "Stakkr Release"
          content: "<@&1412150922632626366>"
          avatar_url: "https://raw.githubusercontent.com/Libnaus/.github/refs/heads/main/profile/assets/img/logo.png"
          footer_title: "Stakkr Release ${{ github.event.release.tag_name }}"
          footer_icon_url: "https://raw.githubusercontent.com/Libnaus/.github/refs/heads/main/profile/assets/img/logo.png"
          footer_timestamp: true
          reduce_headings: true